---
abstract: 'Pegex Parser for JSON'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Pegex::JSON
name: Pegex-JSON
no_index:
  directory:
    - inc
    - t
requires:
  Pegex: 0.21
  boolean: 0.28
  perl: 5.10.0
resources:
  homepage: https://github.com/ingydotnet/pegex-json-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/pegex-json-pm.git
    web: https://github.com/ingydotnet/pegex-json-pm/tree
version: 0.16
